CREATE TABLE DICT (
	TYPE_ID INT NOT NULL,
	TERM_ID BIGINT NOT NULL,
	LOCALE VARCHAR(20) NOT NULL,
	VALUE TEXT NOT NULL,

	PRIMARY KEY (TERM_ID, LOCALE),

	KEY IDX_D_TYPE_ID (TYPE_ID),
	CONSTRAINT FK_D_TYPE_ID FOREIGN KEY (TYPE_ID) REFERENCES DICT_TYPE (ID),

	KEY IDX_D_VALUE (VALUE(100)),
	CONSTRAINT UK_D_VALUE UNIQUE (VALUE(100))
)
