CREATE TABLE TAG (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TERM_ID BIGINT NOT NULL,
	DELETED INT(1) NOT NULL DEFAULT 0,
	CREATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFICATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),

	PRIMARY KEY (ID),

	KEY IDX_T_TERM_ID (TERM_ID),
	CONSTRAINT UK_T_TERM_ID UNIQUE (TERM_ID)
)
