CREATE TABLE TEXT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TEXT LONGTEXT NOT NULL,
	DELETED INT(1) NOT NULL DEFAULT 0,
	CREATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFICATION_TIME TIMESTAMP NOT NULL DEFAULT NOW()
)
