CREATE TABLE USER_HISTORY (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	HISTORY_ACTION_ID INT(4) NOT NULL,
	ACTOR_ID BIGINT NOT NULL,
	CREATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),

	PRIMARY KEY (ID),

	KEY IDX_UH_USER_ID (USER_ID),
	CONSTRAINT FK_UH_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID),

	KEY IDX_UH_HISTORY_ACTION_ID (HISTORY_ACTION_ID),
	CONSTRAINT FK_UH_HISTORY_ACTION_ID FOREIGN KEY (HISTORY_ACTION_ID) REFERENCES HISTORY_ACTION (ID)
)
