CREATE TABLE USER_INFO (
	USER_ID BIGINT NOT NULL,
	NAME VARCHAR(200) DEFAULT NULL,
	GENDER INT(1) NOT NULL DEFAULT 2,
	DOB DATE DEFAULT NULL,
	COUNTRY VARCHAR(100) DEFAULT NULL,
	STATUS VARCHAR(140) DEFAULT NULL,
	AVATAR MEDIUMBLOB DEFAULT NULL,
	HIDDEN INT(1) NOT NULL DEFAULT 1,
	CREATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFICATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),

	PRIMARY KEY (USER_ID),

	CONSTRAINT FK_UI_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
)
