CREATE TABLE USER_ROLE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	ROLE VARCHAR(45) NOT NULL,
	ENABLED INT(1) NOT NULL DEFAULT 1,
	CREATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFICATION_TIME TIMESTAMP NOT NULL DEFAULT NOW(),

	PRIMARY KEY (ID),

	KEY IDX_UR_USER_ID_ROLE (USER_ID, ROLE),
	CONSTRAINT UK_UR_USER_ID_ROLE UNIQUE (USER_ID, ROLE),

	KEY IDX_UR_USER_ID (USER_ID),
	CONSTRAINT FK_UR_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
)
